### ISSUE TITLE
Support specifying render adapter

### ISSUE THREAD

**Issue by PixelyIon** [VirtualDisplay/Virtual-Display-Driver#12]
I'm using this on a laptop with an Intel iGPU as well as an Nvidia dGPU. Windows OS code currently automatically picks my iGPU as the render adapter for the DXGI swapchain which isn't desirable as my iGPU isn't nearly as good at video encoding compared to my dGPU. From a cursory look, a potential fix would involve specifying the desired adapter in the config either by its name or LUID and calling [`IddCxAdapterSetRenderAdapter`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/iddcx/nf-iddcx-iddcxadaptersetrenderadapter) at the start with the GPU's LUID to ensure it's using the right adapter. A tiny utility to enumerate the LUIDs of all GPUs present on the system to go with it would be perfect.

**Comment by zjoasan** [comment]
would this be helpfull? haven't looked at the code to asigne a gpu to the virtual driver:
powershell command:
```
gwmi win32_VideoController | FT Name,AdapterDACType,DeviceID,PNPDeviceID

Name                       AdapterDACType    DeviceID         PNPDeviceID
----                       --------------    --------         -----------
Intel(R) UHD Graphics 630  Internal          VideoController1 PCI\VEN_8086&DEV_3E9B&SUBSYS_1B3E1043&REV_00\3&1158365...
NVIDIA GeForce GTX 1050 Ti Integrated RAMDAC VideoController2 PCI\VEN_10DE&DEV_1C8C&SUBSYS_1B3E1043&REV_A1\4&1378839...
IddSampleDriver Device HDR                   VideoController3 ROOT\DISPLAY\0000
```

**Comment by kayti** [comment]
So is there any way to do it with released driver? I have RTX3080 and T400, wanted to use T400 for encoding, so i could use HAGS with RTX 3080 and FSR3 for frame generation. With HAGS on right now and high gpu utilization the stream is choppy at best :P

**Comment by matheusfaustino** [comment]
You can select the GPU now: https://github.com/itsmikethetech/Virtual-Display-Driver/issues/110#issuecomment-2261267507
