### ISSUE TITLE
[Bug]: Cannot connect moonlight when using VDD

### ISSUE THREAD

**Issue by Peabuttt** [VirtualDisplay/Virtual-Display-Driver#179]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

Hey. 

Im getting an error when connecting moonlight because it cannot initialize the VDD.

```
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Cannot index into a null array.
At D:\Programs\Sunshine\tools\sunshine-virtual-monitor-main\setup_sunvdm.ps1:36 char:1
+ $vdd_name = (
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Setting up a moonlight monitor with 2560x1600@72 with hdr off
Enabling the virtual display.
Get-PnpDevice : Cannot validate argument on parameter 'FriendlyName'. The argument is null. Provide a valid value for 
the argument, and then try running the command again.
At D:\Programs\Sunshine\tools\sunshine-virtual-monitor-main\setup_sunvdm.ps1:76 char:29
+ Get-PnpDevice -FriendlyName $vdd_name | Enable-PnpDevice -Confirm:$fa ...
+                             ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PnpDevice], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-PnpDevice
 
Setting up the virtual display and disabling other displays.
Disabling all other displays.
Failed to disable all other displays.
At D:\Programs\Sunshine\tools\sunshine-virtual-monitor-main\setup_sunvdm.ps1:112 char:9
+         Throw "Failed to disable all other displays."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to disable all other displays.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to disable all other displays.
```

I dont have nvidia so the missing dll is fine.

![{54C63B93-2D33-46BE-A89A-FBD1B6FCCA85}](https://github.com/user-attachments/assets/208ee923-cb5e-450f-ba49-38819eaf4be0)

Can some1 help?

EDIT: looks like VDD was not correctly installed and the virtual display had no name. I fixed that but I still have errors.

```
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Failed to load "nvapi64.dll". Error: The specified module could not be found.
Setting up a moonlight monitor with 2560x1600@72 with hdr off
Enabling the virtual display.
Setting up the virtual display and disabling other displays.
Disabling all other displays.
Failed to disable all other displays.
At D:\Programs\Sunshine\tools\sunshine-virtual-monitor-main\setup_sunvdm.ps1:112 char:9
+         Throw "Failed to disable all other displays."
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to disable all other displays.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to disable all other displays.
```

**Comment by zjoasan** [comment]
I'm draw the conclusion that this isn't a VDD issue, when you clearly show that your computer identifies 2 GPUs from AMD, the one in the CPU and the RX 7900. But is trying to load Nvidia libraries? Check your sunshine settings

**Comment by Peabuttt** [comment]
I don't see any issues with sunshine configuration. Can you elaborate what exactly I'm looking for? In fact, the only thing that is not drfault setting is the start and stop script for VDD

**Comment by zjoasan** [comment]
"nvapi64.dll" is an Nvidia dynamic libary, which sunshine or that script is trying to load. If you don't have an nvidia card you wont have those in the system. So by the information you have show, either sunshine is configured to use nvidia or the script is?

**Comment by itsmikethetech** [comment]
As a possible solution, you could check Sunshine encoder settings. There are settings for Nvidia, AMD, Intel, and Software-based Encoding. You'll want to enable AMD for your system.

**Comment by Peabuttt** [comment]
you are not going to believe, but the problem was my second screen. I have no idea why but because my 2nd screen is flipped, the script to turn off/on the monitors was not able to complete.

i just had to turn it off manually 1 time, and now the script is able to do it all. cant understand but that what happened.

**Comment by itsmikethetech** [comment]
Weird! Glad you got it sorted.
