### ISSUE TITLE
Best method to update

### ISSUE THREAD

**Issue by Simzy** [VirtualDisplay/Virtual-Display-Driver#184]
So i use your virtual display for Sunshine/Moonlight and have found it invaluable but the version i have is your actual release one, i was wondering if it was as simple as downloading the new files, renaming to the ones i currently have and then overwrite for updating them as i installed everything using the Sunshine AIO script for the auto disable of monitors when connected.

**Comment by itsmikethetech** [comment]
Basically. Uninstall using device manager. Delete or replace the files with the new driver (note that the beta has a new location). Run the certificate script, then add it back in device manager.

**Comment by itsmikethetech** [comment]
We also have an installer and companion software coming soon to streamline this process further.

**Comment by bud3699** [comment]
Or if you need to keep it installed but update it, copy the files first, right click the driver and click update then update from file and select the new files
