### ISSUE TITLE
Trying the version with adapter.txt the certificate is expired. The new versions do not come with adapter.txt

### ISSUE THREAD

**Issue by joeldq** [VirtualDisplay/Virtual-Display-Driver#188]
Do we know if the new versions include the feature? I do not see on the release notes.

**Comment by bud3699** [comment]
The gpu is set in the xml

**Comment by tribhoon** [comment]
> The gpu is set in the xml

Could you please explain how?

The latest version also doesn't come with an xml, does it? I tried adding an xml file myself but that doesn't seem to change anything.

**Comment by jdiazquiroga** [comment]
I figured out you need to use the latest beta versions The versions on the front do not include it 
![image](https://github.com/user-attachments/assets/5ca3e9dd-fb70-450c-a7a2-6bda776799f9)

And the version 24.7.18 (which does include adapter.txt) has an expired certificate. It was a bit unclear as it wasn't explained well on the other topics similar to this.

**Comment by tribhoon** [comment]
> I figured out you need to use the latest beta versions The versions on the front do not include it ![image](https://private-user-images.githubusercontent.com/77779398/386662685-5ca3e9dd-fb70-450c-a7a2-6bda776799f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2ODU1NzgsIm5iZiI6MTczMTY4NTI3OCwicGF0aCI6Ii83Nzc3OTM5OC8zODY2NjI2ODUtNWNhM2U5ZGQtZmI3MC00NTBjLWE3YTItNmJkYTc3Njc5OWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE1NDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNDNiNmFkNDRkYjI5ZDFkNjJhOTNkOWI0MTk3OGE3YjBiYzkxZDNkMmI1ZTgxMDEyMzg5OWNmMDI0OTk5YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j25JxCFPbiIHAuoOfRklPSTKytMhROrLe6W9adrWb5Y)
> 
> And the version 24.7.18 (which does include adapter.txt) has an expired certificate. It was a bit unclear as it wasn't explained well on the other topics similar to this.

Thank you!! Editting the xml in the beta version worked. Appreciate your help

**Comment by itsmikethetech** [comment]
The certificates on both the stable release and beta should now have new certificates attached.
