### ISSUE TITLE
Does Virtual Display Driver reduce hardware life?

### ISSUE THREAD

**Issue by kaedee206** [VirtualDisplay/Virtual-Display-Driver#218]
I wonder if VDD reduce hardware life xd thx for answer

**Comment by zjoasan** [comment]
My intuitive answer is: "Just as much as Microsoft word or a screenhot app that runs in the background 24/7 does.

It's just another piece of software running on a hardwareplatform built for running software.

I have a hard time comming up with a reason for even comming close to such an idea, could you explain your reasoning? I'm truely interested if I missed something in my reasoning.

**Comment by itsmikethetech** [comment]
The Virtual Display Driver (VDD) itself is a software-based solution, so it does not directly affect hardware lifespan. However, its  system resource requirements can have indirect effects on hardware longevity, for example your GPU working harder to display a 4k image over a 1080p image.
