### ISSUE TITLE
[Bug]:  VDD used with Sunshine (Moonlight host)

### ISSUE THREAD

**Issue by IfEyeCouldCode** [VirtualDisplay/Virtual-Display-Driver#224]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

Hi, sorry to bother again but I've ran into a scenario that's causing quite some confusion.
In LizardBytes documentation regarding Sunshine, the program choses a graphics card AND then a display to capture.
AMD RX 590 automatically detected and implied, along with my primary display.

I downloaded VDD to have the freedom of streaming my secondary monitor on windows, but I'm running into an error on moonlight and after looking into it i think-
The secondary monitor (VDD spoof monitor) isn't showing up because its... not being captured or processed by my GPU? 

I swear I've done this before, and i know plenty of people use VDD for this purpose, so is there something obvious I'm forgetting to fix?

Summary: i wanna use VDD to create a secondary monitor, which i can stream to my ipad, but I'm not sure how to.

**Comment by itsmikethetech** [comment]
Did you set the Display Sink in the Sunshine Configuration?

**Comment by IfEyeCouldCode** [comment]
> Did you set the Display Sink in the Sunshine Configuration?

not seeing that option, only audio sync. Is this under a separate tab?

**Comment by itsmikethetech** [comment]
![image](https://github.com/user-attachments/assets/9bb046a9-59c7-4ed4-8e1b-657a68336ef2)

**Comment by IfEyeCouldCode** [comment]
> Apologies, it's called Output here:
> 
> ![image](https://private-user-images.githubusercontent.com/25166211/397901229-9bb046a9-59c7-4ed4-8e1b-657a68336ef2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTA4NzcsIm5iZiI6MTczNDc1MDU3NywicGF0aCI6Ii8yNTE2NjIxMS8zOTc5MDEyMjktOWJiMDQ2YTktNTljNy00ZWQ0LThlMWItNjU3YTY4MzM2ZWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzMDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZjJkNzA1ZWI0NGI0MjAwMzdlOWJhN2FiZDVkMDEwNjM1MzQzZjQwOTYxNzQyZmQ0MGE1ODk4MTc2NWM2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1CKrYCQLW9cPcwtej1ZlBfx1gexONYFx9CeI9ZRr1xk)

ahh yep! i tried inputting "\\.\DISPLAY2" with no luck which really confused me.

**Comment by itsmikethetech** [comment]
You'll need to use the dxgi tool that comes with sunshine to figure out the display ID. It's not always 2. 

Try running this in Powershell:

`irm scripts.mikethetech.com/display | iex`

**Comment by IfEyeCouldCode** [comment]
LMAOOOOO no way. First off thank u for that script wtf, is that using the database/website you made? It totally worked XD I'm just totally shocked that
1. The VD got pushed all the way down to "DISPLAY-8" 
2. The LizardByte team doesn't link any troubleshoot tools like that.

Thanks Mike !

**Comment by itsmikethetech** [comment]
Bud made the EDID Database, but nah. This just downloads the DXGI tool that already comes with Sunshine and runs it locally. lol. Hosted it on my server to make it super easy to run even if sunshine isn't installed. :) Glad it worked for you!

**Comment by IfEyeCouldCode** [comment]
dude no way lmao I have been running "dxgi-info.exe" for hours from the sunshine folder but the cmd window would open, fill out all the data, and immediately close before i could read anything. I opened an issue on their Discord server but idk if their dxgi from their release is truly bugged or my pc is just fucked up. 

Either way thanks loads you just saved me from breaking my keyboard ^_^

Novice question but can i copy/download it anywhere so i can run it locally in the future?

**Comment by itsmikethetech** [comment]
It's actually the same file. So the way to properly run it, is to open the folder it's in (Sunshine/tools/), then open a command prompt terminal and ensure it's in the proper directory. You can do this by typing "Powershell" or "cmd" into the top bar of file explorer and pressing enter. Your cmd prompt should show something like C:\Program Files\Sunshine\Tools\>

Once it does, type in the name of the tool, like dxgi-info.exe or whatever it happens to be, and press enter. This will stop the window from closing.

Alternatively, you can drag the exe into an open command prompt window and hit enter.
