### ISSUE TITLE
[Bug]: Unable to set 3440x1440 60 HZ

### ISSUE THREAD

**Issue by FatCache** [VirtualDisplay/Virtual-Display-Driver#227]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

Pretty much title. I am not sure what I am doing wrong. Help will be appreciated. **The option to set 3440x1440 does not display in Display Setting Menu**

my options.txt file in c:/idm... directory

```
1920, 1080, 30
1920, 1080, 60
1920, 1080, 75
1920, 1080, 90
1920, 1080, 120
1920, 1200, 60
1920, 1440, 60
2560, 1440, 60
2560, 1440, 120
3440, 1440, 60
3840, 2160, 60
3840, 2160, 120
```

I customized vdd_settings.xml file as well and added the following XML tag

```
		 <resolution>
            <width>3440</width>
            <height>1440</height>
            <refresh_rate>30</refresh_rate>
            <refresh_rate>60</refresh_rate>
            <refresh_rate>90</refresh_rate>
            <refresh_rate>120</refresh_rate>
            <refresh_rate>144</refresh_rate>
            <refresh_rate>165</refresh_rate>
        </resolution>
```

Note: i have installed and installed previous version of this driver from previous fork and this fork. My uninstall method has been to remove the driver using device manager.

**Comment by itsmikethetech** [comment]
The beta uses the C:\VirtualDisplayDriver directory now. Not the IddSampleDriver directory.

**Comment by itsmikethetech** [comment]
You'll want to ensure the XML file is in that directory, then restart the driver.

**Comment by FatCache** [comment]
I see. Thanks. I missed that part.
