### ISSUE TITLE
need help/(ㄒoㄒ)/

### ISSUE THREAD

**Issue by sadsora** [VirtualDisplay/Virtual-Display-Driver#231]
After I installing VDD, I use some remote control software to control my PC. But it has two cursors overlapping on my screen. And when I move my cursor, one cursor moves after the other. It looks very annoying. And I have ruled out any software-related issues. So  will it be the VDD's problem? If it does, could you guys help me figure it. Thanks.
![e9c3d20c7ab44176c9e8d286e699d5c](https://github.com/user-attachments/assets/1e8f1a44-c0ea-49f8-a332-1bd5a2e7ecdb)

**Comment by itsmikethetech** [comment]
You can turn off the hardware cursor in the companion app or the XML config.
