### ISSUE TITLE
Uninstall issue

### ISSUE THREAD

**Issue by flaccidpotato1327** [VirtualDisplay/Virtual-Display-Driver#232]
I uninstalled the driver from device manager then uninstalled the program from the uninstall menu and now can't reinstall the software or drivers. When I try to run the installer I get a prompt to uninstall. Then it says it can't find the registry file for the uninstall and then says it will exit. I included screenshots of the prompt. 
![Capture2](https://github.com/user-attachments/assets/e899136a-386c-4ce1-862c-118ab5ea4d56)
![Capture1](https://github.com/user-attachments/assets/f2008bac-3f3e-43b4-9330-517f52f880ef)
![Capture](https://github.com/user-attachments/assets/f02e9202-e275-49ad-9421-1c2241879d86)

**Comment by bud3699** [comment]
if thats the case go to control panel or settings, go to uninstall a program and uninstall it from there, it might say "cant find uninstaller would you like to delete this shortcut" then click yes and you should be able to install it again

**Comment by flaccidpotato1327** [comment]
I tried that already. It no longer shows up in the control panel. It also no longer shows up as a device in device manager.

**Comment by bud3699** [comment]
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\MikeTheTech\VirtualDisplayDriver`


delete this reg key then

**Comment by flaccidpotato1327** [comment]
Thank you so much. I was looking for the reg key and didnt realize it was under mikethetech. That fixed the problem.
