### ISSUE TITLE
[Bug]: Some games during streaming only maxed out at 30hz

### ISSUE THREAD

**Issue by RebelliousX** [VirtualDisplay/Virtual-Display-Driver#234]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

Despite specifying that I want 60hz in display settings. Moonlight when showing statistics and MSI after burner show that max FPS is 30FPS.

Sunshine logs show Display Refresh Rate is 30hz while request refresh rate is 60hz.

I am using latest installer that was released before the holidays few days ago. 

Looking at the ZIP signed installer. I see bunch of resolutions are all defaulting to 30hz 
I uninstalled the installer version and used manual installation. Modified the XML to have
minimum 60hz and issue is fixed in gameplay, much smoother than the nauseating and  jarring 30hz.

### ***Is there a way to install the Companion Startup App with manual installation of driver?***

Here is a snippet of the default XML file in the Zip file of signed driver:

```xml
<global>
		<!--These are global refreshrates, any you add in here, will be replicated to all resolutions-->
		<g_refresh_rate>60</g_refresh_rate>
		<g_refresh_rate>90</g_refresh_rate>
		<g_refresh_rate>120</g_refresh_rate>
		<g_refresh_rate>144</g_refresh_rate>
		<g_refresh_rate>165</g_refresh_rate>
		<g_refresh_rate>244</g_refresh_rate>
	</global>
    <resolutions>
        <resolution>
            <width>800</width>
            <height>600</height>
            <refresh_rate>30</refresh_rate>
        </resolution>
        <resolution>
            <width>1366</width>
            <height>768</height>
            <refresh_rate>30</refresh_rate>
        </resolution>
        <resolution>
            <width>1920</width>
            <height>1080</height>
            <refresh_rate>30</refresh_rate>
        </resolution>
        <resolution>
            <width>2560</width>
            <height>1440</height>
            <refresh_rate>30</refresh_rate>
        </resolution>
        <resolution>
            <width>3840</width>
            <height>2160</height>
            <refresh_rate>30</refresh_rate>
        </resolution>
    </resolutions>
```

**Comment by bud3699** [comment]
You can still configure the xml file with the installer ? It goes to the location of where you installed the driver to

**Comment by RebelliousX** [comment]
@bud3699 good to know that. 

Again the issue happens with some of my games, others default to 60hz. But manually adjusting the XML fixes that.

The list of supported refresh rates start with 60 and up. I am not sure why 30hz is the default for all listed resolutions here anyways This is what is causing the problem.

**Comment by bud3699** [comment]
30 is the default just to keep compatibility with lower end devices. We have no idea the full user base so it's safer to default to lowest and anyone who requires otherwise can configure it to their preferences

**Comment by RebelliousX** [comment]
I see. But the companion app should able to override / overwrite these settings in my opinion.

About master / slave terminology, it is all about context. We are talking technical terms not about people. I really don't like how the world is going sensitive and hurt about everything these days. Even github changed the name of master branch to main due to that. But I digress.

Again, the companion app should override these settings in my opinion than letting user to modify XML manually.

**Comment by bud3699** [comment]
Yup! Don't worry this will come, I was just a bit pressed for time for the first release. But don't worry, it will be coming :)

**Comment by RebelliousX** [comment]
Thanks 👍🏻

**Comment by bud3699** [comment]
No problemo! Is that everything? May I close this issue now ?

**Comment by RebelliousX** [comment]
Yes. Thanks.
