### ISSUE TITLE
[Bug]: Cant Uninstall

### ISSUE THREAD

**Issue by Bar-innutshell** [VirtualDisplay/Virtual-Display-Driver#238]
### Which OS?

Win11 Pro

### Which release?

24H2

### Describe the bug

i click the uninstall.bat and now when i wanna install again it just give me a pop up already install and failed to uninstall and immediately exit

### Expected behavior

can install aagain

**Comment by bud3699** [comment]
You uninstal via the control panel/settings or running installer again. not by running the  bat file

https://github.com/VirtualDisplay/Virtual-Display-Driver/wiki/Uninstalling-Virtual-Display-Driver

**Comment by anders0821** [comment]
I encountered the same thing

**Comment by itsmikethetech** [comment]
> I encountered the same thing. Now I cannot use this software anymore.

**Steps to Remove Registry Keys:**

1. Press Windows + R to open the Run dialog.
2. Type regedit and press Enter to open the Registry Editor.
3. Navigate to the following registry path:
4. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\MikeTheTech\VirtualDisplayDriver
5. Right-click on the VirtualDisplayDriver key and select Delete.
6. Confirm the deletion by clicking Yes.

Warning: Editing the registry can cause issues with your system if not done correctly. It’s important to back up the registry before making any changes.
