### ISSUE TITLE
Any way to support HDR or 10-bit color depth on Win10 ?

### ISSUE THREAD

**Issue by MooooonPrism** [VirtualDisplay/Virtual-Display-Driver#32]
Amazing job! And this works on my win11. But is there any way to support Win10?
I need to create a virtual monitor which supports HDR(actually I need **10-bit color depth**) using IDD or other virtual display driver, but it must work on **Win10**. Could anyone give me any guidance on this issue ?

**Comment by carpeggios** [comment]
Not likely; 

https://github.com/roshkins/IddSampleDriver/issues/23#issuecomment-1345820453

**Comment by itsmikethetech** [comment]
Unfortunately, not unless Windows releases IddCx 1.10 for Windows 10. Until then, we're basically at their mercy.
