### ISSUE TITLE
Implement decimal/ float point refresh rates?

### ISSUE THREAD

**Issue by bytat** [VirtualDisplay/Virtual-Display-Driver#40]
Would it be possible to implement refresh rates like 60.01 Hz? I had microstutter on 60hz, probably because 59.96 Hz mismatch of some kind and I managed to solve it with a custom 60.01 Hz on my hdmi dummy plug created with nvidia control panel. Alas no hdr that way.

**Comment by bud3699** [comment]
I'll say, that's a bit odd. I can possibly take a look for you if you'd like

**Comment by bytat** [comment]
Thanks, would you? Il’d really apreciate it! 🙂

**Comment by bud3699** [comment]
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/75859057/2ca18b49-7bb9-4d9a-b0b1-8b71057b7756)

Might not be possible as of yet. Mike tested with 59.94 and it just displays as 59

**Comment by DzmitryTheStreak** [comment]
That would be awesome!

My Android TV box is limited to 59.94Hz and because of that I'm getting stutters as well.

**Comment by bud3699** [comment]
> That would be awesome!
> 
> My Android TV box is limited to 59.94Hz and because of that I'm getting stutters as well.



I will take a look at the code tonight. See if its easily changeable

**Comment by bytat** [comment]
Any news regarding this?

**Comment by itsmikethetech** [comment]
Fractional refresh rates are now supported in the beta driver.

**Comment by bytat** [comment]
Thanks a lot!

**Comment by bud3699** [comment]
I added it a while back but tend to forget to respond to issues. If you're fussed about recieving updates when they're released you can probably just watch the repo

**Comment by bytat** [comment]
No problem, I saw it back when. I just thought that a thank you for your guys hard work was in order now that you mentioned it.
