### ISSUE TITLE
connected to integrated graphics card and poor performance

### ISSUE THREAD

**Issue by TheFourthRome** [VirtualDisplay/Virtual-Display-Driver#41]
My laptop has integrated graphics card and Nvidia GPU, and it works on integrated graphics, so that the performance is very poor.it only connects to the Nvidia GPU when I disable the integrated graphics.

**Comment by matheusfaustino** [comment]
change to the GPU using this: https://github.com/itsmikethetech/Virtual-Display-Driver/issues/110#issuecomment-2261267507
