### ISSUE TITLE
Screen output is black?

### ISSUE THREAD

**Issue by aqwasch** [VirtualDisplay/Virtual-Display-Driver#50]
I installed just like the way in the video, but the display settings were automatically set to 'duplicate'. when i set to show the second screen, my screen blacked out. Anyone knows what might be the problem?

**Comment by averagejooe** [comment]
If you ever use a dummy HDMI plug, then this utility behaviour is actually consistent just like the real thing. As the function is to create a virtual display, which interface can be seen remotely via Parsec/Moonlight etc. 
But yea I wish it were possible to display more than 1080p to my office monitor and old miniPC so I can have more screen estate natively. Today I also tried using CRU where you can add detailed resolutions, but no luck displaying more than 1080p yet sadly. If you ever stumbled upon a solution, please do lemme know yea :)

**Comment by itsmikethetech** [comment]
You can't view the screen on your main screen without a software solution like OBS. This is normal functionality. You can only duplicate the real monitor onto the virtual one.
