### ISSUE TITLE
VDD is detected under device manager but not under display settings.

### ISSUE THREAD

**Issue by seabird12345** [VirtualDisplay/Virtual-Display-Driver#92]
![VDD](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/170771466/f675fec2-c9c6-4b71-af5c-62e98b65a983)

**Comment by NamerPolice** [comment]
same problem

**Comment by NamerPolice** [comment]
u install win 10 drivers?

**Comment by seabird12345** [comment]
no, I have Windows 11 Version 22H2

**Comment by seabird12345** [comment]
![2](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/170771466/a0e0dd14-605b-4a92-8ab7-c6bd40f6336f)

Weird but when I install the non-HDR version, both show up but HDR option is not available.

**Comment by smokybroom** [comment]
Iv got this issue as well.

**Comment by u-tung** [comment]
I encountered the same issue, the reason is that I am using Windows 10 but installed the latest version 23.12.2. Installing version 23.10.20.2 works fine.

By the way, like @seabird12345 mentioned, after installing the correct version, version 23.12.2 devices can be used normally. Maybe the latest version just lacks an activation step for the devices???

**Comment by theretohere** [comment]
I am having the same issue on Win10. I installed beta 24.8.6 as it looked like a unified win10/11 hdr/nonhdr driver. I get a device is not working properly, Code 31, and the driver in Device Manager says "Virtual Display with HDR Properties". 

I tried to install 23.10.20.2, and the driver name does not include HDR, and the adapter in Device Manager looks okay, but there is nothing new showing in the Windows Display settings. Restarted computer, restarted device, nothing.

**Comment by bud3699** [comment]
If people can try with the latest beta and provide logs where possible, this would help us diagnose the issue, most likely an issue with windows itself. But without direct access to logs its hard to diagnose

You can enable logging by toggling logging in vdd_settings.xml. Please do this before installing the driver to prevent needing to restart the device or driver

**Comment by monkeychunki** [comment]
same issue with Win11

**Comment by bud3699** [comment]
> same issue with Win11, although i'm now receiving the below error
> 
> ![Screenshot 2024-10-23 193054](https://github.com/user-attachments/assets/6e36b5a7-d581-4ba5-b499-fc1d5f4cd6b5)
> 
> 
> 
> 

Did you try the beta

**Comment by monkeychunki** [comment]
yep & its now working. Thanks !
